#
site_routes:
    resource: '../../src/Controller/Action'
    defaults:
        _locale: lv
    type: annotation
#
sitemap:
    resource: App\Controller\SitemapController
    type: annotation
#
app:
    resource: App\Routing\SiteRoutes:loadRoutes
    type: service
