# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    upload_directory: '%kernel.project_dir%/src/Shared/Uploads'
    upload_public_path: '/uploads/'

webpack_encore:
    output_path: '%kernel.project_dir%/public/admin/build'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
          # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Admin,Controller,Exception,Helpers,Resources,Routing,Services,Shared,AdminKernel.php,SiteKernel.php}'

    # SHARED
    Shared\:
        resource: '../src/Shared/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # SHARED/LISTENERS
    Shared\EventListener\TraceabilityListener:
        arguments: ['@security.token_storage']
        tags:
            - { name: 'doctrine.event_listener', event: preUpdate}
            - { name: 'doctrine.event_listener', event: prePersist}

    Admin\:
        resource: '%kernel.project_dir%/src/Admin/*'
        exclude: '%kernel.project_dir%/src/Admin/{Exception,Form,Service,Security}'

    # ADMIN CONTROLLER
    Admin\Controller\:
        resource: '%kernel.project_dir%/src/Admin/Controller/*'
        tags: ['controller.service_arguments']

    # ADMIN SERVICES
    Admin\Service\:
        resource: '%kernel.project_dir%/src/Admin/Service/*'
        arguments: ['@doctrine.orm.entity_manager']

    Admin\Service\SettingService:
        arguments: ['@doctrine.orm.entity_manager']

    Admin\Security\AccessDeniedHandler:
        arguments: ['@templating.engine.php']

    Admin\Service\PageManageService:
        arguments: ['@doctrine.orm.entity_manager','@Admin\Service\FileUploader']

    Admin\Service\PostManageService:
        arguments: ['@doctrine.orm.entity_manager','@Admin\Service\FileUploader']

    Admin\Service\FileUploader:
        arguments:
          ['%upload_directory%','@Admin\Service\StorageService']

    # ADMIN FORMS
    Admin\Form\:
        resource: '%kernel.project_dir%/src/Admin/Form/*'
        arguments: ['@doctrine.orm.entity_manager']
        tags: [name: controller.service_arguments]

    Admin\Form\MenuForm:
        arguments: ['@doctrine.orm.entity_manager', '@Admin\Service\FileUploader']

    Admin\Form\PageSettingsForm:
        arguments: ['@doctrine.orm.entity_manager', '@Admin\Service\FileUploader']

    Admin\Form\PageBlockSettingsForm:
        arguments: ['@doctrine.orm.entity_manager', '@Admin\Service\FileUploader']

    # ADMIN HELPERS
    Admin\Helpers\:
        resource: '%kernel.project_dir%/src/Admin/Helpers/*'

    Admin\Helpers\SettingsHelper:
        arguments: ['@templating.engine.php', '@Admin\Service\SettingService']
        tags:
            - { name: templating.helper, alias: settings }

    Admin\Helpers\CategoryHelper:
        arguments: ['@templating.engine.php', '@Admin\Service\SettingService', '@Admin\Service\CategoryService']
        tags:
            - { name: templating.helper, alias: category }