parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Admin,Resources,Shared,AdminKernel.php,SiteKernel.php}'

    # ROUTER
    App\Routing\SiteRoutes:
        public: true
        arguments: ['@App\Services\SettingService', '@doctrine.orm.entity_manager']

    # SERVICES
    App\Services\:
        resource: '../src/Services/*'
    App\Services\SettingService:
        arguments: ['@doctrine.orm.entity_manager', '%kernel.project_dir%']
    App\Services\LocaleService:
        arguments: ['@App\Services\SettingService', '@router']
    App\Services\RequestPageService:
        arguments: ['@doctrine.orm.entity_manager', '@router']

    # HELPERS
    App\Helpers\:
        resource: '../src/Helpers/*'
    App\Helpers\MenuHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService', '@doctrine.orm.entity_manager']
        tags:
        - { name: templating.helper, alias: menu }
    App\Helpers\PageHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: page }
    App\Helpers\PostHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: post }
    App\Helpers\LayoutHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: layout }
    App\Helpers\LocaleHelper:
        arguments: ['@App\Services\LocaleService']
        tags:
        - { name: templating.helper, alias: locale }
    App\Helpers\ThemeHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: theme }
    App\Helpers\SettingsHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
            - { name: templating.helper, alias: settings }
    App\Helpers\TranslHelper:
        arguments: ['@templating.engine.php', '@Admin\Service\TranslationService']
        tags:
            - { name: templating.helper, alias: transl }
