# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app.locales: en|lv
    upload_directory: '%kernel.project_dir%/src/Shared/Uploads'
    upload_public_path: '/uploads/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/Site/*'
        exclude: '../src/Site/{Admin,Resources,Shared,AdminKernel.php,SiteKernel.php}'

    # CONTROLLER
    App\Controller\IndexController:
        tags: ['controller.service_arguments']

    # ROUTER
    App\Routing\SiteRoutes:
        public: true
        arguments: ['@App\Services\SettingService', '@doctrine.orm.entity_manager']

    # SERVICES
    App\Services\:
        resource: '../src/Site/Services/*'
    App\Services\SettingService:
        arguments: ['@doctrine.orm.entity_manager', '%kernel.project_dir%']
    App\Services\LocaleService:
        arguments: ['@App\Services\SettingService', '@router']
    App\Services\RequestPageService:
        arguments: ['@doctrine.orm.entity_manager', '@router']

    # HELPERS
    App\Helpers\:
        resource: '../src/Site/Helpers/*'
    App\Helpers\MenuHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService', '@doctrine.orm.entity_manager']
        tags:
        - { name: templating.helper, alias: menu }
    App\Helpers\PageHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: page }
    App\Helpers\PostHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: post }
    App\Helpers\LayoutHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: layout }
    App\Helpers\LocaleHelper:
        arguments: ['@App\Services\LocaleService']
        tags:
        - { name: templating.helper, alias: locale }

    App\Helpers\ThemeHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
        - { name: templating.helper, alias: theme }

    App\Helpers\SettingsHelper:
        arguments: ['@templating.engine.php', '@App\Services\SettingService']
        tags:
            - { name: templating.helper, alias: settings }

    # SHARED
    Shared\:
        resource: '../src/Shared/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]